In [1]:
import numpy as np

In [2]:
ceny = np.array([
    [29.99, 31.99, 28.99],
    [49.99, 52.99, 47.99],
    [14.99, 15.99, 13.99],
    [99.99, 104.99, 94.99]
])

ceny_inflacja = ceny * 1.05
print(ceny_inflacja)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [3]:
rabaty = np.array([0.10, 0.05, 0.15])
ceny_rabat = ceny * (1 - rabaty)
print(ceny_rabat)

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


In [4]:
rabaty = np.array([0.10, 0.05, 0.15])
ceny_rabat = ceny * (1 - rabaty)
print(ceny_rabat)

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


In [5]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt = ceny / (1 + marza)
print(koszt)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


In [7]:
sklepy = ['Centrum', 'Galeria', 'Online']

najtanszy_idx = ceny.argmin(axis=1)
najtansze = [sklepy[i] for i in najtanszy_idx]

print(najtansze)

['Online', 'Online', 'Online', 'Online']


In [8]:
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

kwartaly = dane_flat.reshape(4, 3)

print("Kwartały:")
print(kwartaly)

print("Suma per kwartał:", kwartaly.sum(axis=1))
print("Najlepszy kwartał:", kwartaly.sum(axis=1).argmax() + 1)

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: 4


In [9]:
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

wszystkie = np.vstack([warszawa, krakow, wroclaw])

print("Macierz:")
print(wszystkie)

print("Suma per oddział:", wszystkie.sum(axis=1))
print("Suma per kwartał:", wszystkie.sum(axis=0))

Macierz:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [10]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])

macierz = sprzedaz_flat.reshape(6, 2)

srednia = macierz.mean(axis=1)
zmiana = macierz[:, 1] - macierz[:, 0]

print("Średnia per produkt:", srednia)
print("Zmiana między miesiącami:", zmiana)

Średnia per produkt: [150. 225. 215. 170. 240. 225.]
Zmiana między miesiącami: [100 150 -70 100 140 -70]


In [11]:
flat = kwartaly.flatten()
nowe = np.concatenate([flat, np.array([235])])

print("Po dodaniu 13 miesiąca:")
print(nowe)

Po dodaniu 13 miesiąca:
[120 135  98 142 167 189 201 178 156 143 198 221 235]


In [12]:
np.random.seed(2026)

pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

In [13]:
print("Średnia:", pensje.mean())
print("Mediana:", np.median(pensje))
print("STD:", pensje.std())

nazwy = np.array(pracownicy)

print("Powyżej średniej:", nazwy[pensje > pensje.mean()])
print("Poniżej mediany:", nazwy[pensje < np.median(pensje)])

iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print("IQR:", iqr)

Średnia: 6425.0
Mediana: 6050.0
STD: 1616.9029037020127
Powyżej średniej: ['Jan' 'Marek' 'Zofia']
Poniżej mediany: ['Anna' 'Ewa' 'Piotr' 'Tomek']
IQR: 2200.0


In [14]:
premia = np.where(oceny >= 4.5, 2000,
         np.where(oceny >= 4.0, 1000, 0))

nowe_wynagrodzenie = pensje + premia

print("Premie:", premia)
print("Najwyższa premia:", pracownicy[premia.argmax()])

Premie: [1000    0 2000 1000 2000    0 1000    0]
Najwyższa premia: Ewa


In [15]:
kolejnosc = np.argsort(pensje)[::-1]

for i, idx in enumerate(kolejnosc, 1):
    print(i, pracownicy[idx], pensje[idx], staz[idx])

1 Marek 9100 15
2 Zofia 8500 12
3 Jan 7200 8
4 Kasia 6300 5
5 Tomek 5800 4
6 Anna 5500 3
7 Ewa 4800 2
8 Piotr 4200 1


In [16]:
corr1 = np.corrcoef(staz, pensje)[0, 1]
corr2 = np.corrcoef(staz, oceny)[0, 1]

print("Staż vs pensja:", corr1)
print("Staż vs ocena:", corr2)

Staż vs pensja: 0.987862864584301
Staż vs ocena: 0.04198471605953067


In [17]:
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

print("Najlepszy produkt:", przychod.sum(axis=1).argmax())
print("Najlepszy miesiąc:", przychod.sum(axis=0).argmax())

print("Pierwsze 3 miesiące:", przychod[:, :3].sum())
print("Ostatnie 3 miesiące:", przychod[:, 3:].sum())

Najlepszy produkt: 2
Najlepszy miesiąc: 1
Pierwsze 3 miesiące: 2463950
Ostatnie 3 miesiące: 2536500


In [19]:
np.random.seed(42)

wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

In [20]:
print("Wiek:", wiek.mean(), np.median(wiek), wiek.std(), wiek.min(), wiek.max())
print("Wydatki:", wydatki.mean(), np.median(wydatki), wydatki.std())

print("Korelacja wiek-wydatki:", np.corrcoef(wiek, wydatki)[0,1])
print("Korelacja wizyty-wydatki:", np.corrcoef(wizyty, wydatki)[0,1])

sr = wydatki.mean()
sd = wydatki.std()

segment = np.where(wydatki > sr + sd, 'WYSOKI',
          np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

unikalne, liczby = np.unique(segment, return_counts=True)

print(dict(zip(unikalne, liczby)))

Wiek: 33.63 33.0 8.643673987373656 18 53
Wydatki: 504.4609174099847 516.8214339893668 189.7777281021292
Korelacja wiek-wydatki: -0.12009183441777695
Korelacja wizyty-wydatki: -0.15884985147948122
{np.str_('NISKI'): np.int64(17), np.str_('WYSOKI'): np.int64(12), np.str_('ŚREDNI'): np.int64(71)}
