# Laboratorium 3 — NumPy
Autor: Lukasz Nizynski

In [1]:
import numpy as np

In [2]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])

print("Oceny:", oceny)
print("Typ:", oceny.dtype)

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
zera = np.zeros(10)

print("Zera:", zera)

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
jedynki = np.ones((3,5))

print("Jedynki:")
print(jedynki)

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
dziesiatki = np.arange(0,101,10)

print("Dziesiątki:", dziesiatki)

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
ulamki = np.linspace(0,1,7)

print("Ułamki:", ulamki)

Ułamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
np.random.seed(42)

losowe_oceny = np.random.randint(2,6,size=20)

print("Losowe oceny:", losowe_oceny)

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [8]:
print("shape:", losowe_oceny.shape)
print("ndim:", losowe_oceny.ndim)
print("size:", losowe_oceny.size)
print("dtype:", losowe_oceny.dtype)

shape: (20,)
ndim: 1
size: 20
dtype: int64


In [9]:
miesiace_sprzedaz = np.array([120,135,98,142,167,189,201,178,156,143,198,221])

In [10]:
print(miesiace_sprzedaz[0])

120


In [11]:
print(miesiace_sprzedaz[-1])

221


In [12]:
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [13]:
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [14]:
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [15]:
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


In [16]:
dane = np.array([
[120,145,167],
[89,102,95],
[234,267,289],
[56,78,91]
])

produkty = ['Produkt A','Produkt B','Produkt C','Produkt D']
kwartaly = ['Q1','Q2','Q3']

In [17]:
print(dane[0,1])

145


In [18]:
print(dane[2])

[234 267 289]


In [19]:
print(dane[:,0])

[120  89 234  56]


In [20]:
print(dane[1:3,1:3])

[[102  95]
 [267 289]]


In [21]:
nazwy = ['Laptop','Tablet','Smartfon','Słuchawki','Ładowarka',
'Klawiatura','Mysz','Monitor','Kamera','Drukarka']

ceny = np.array([3499,1899,2499,349,89,249,129,1499,599,899])

ilosci_magazyn = np.array([15,42,78,156,312,89,201,23,45,34])

oceny_klientow = np.array([4.7,4.2,4.5,4.8,3.9,4.1,4.3,4.6,3.8,3.5])

In [22]:
nazwy = ['Laptop','Tablet','Smartfon','Słuchawki','Ładowarka',
'Klawiatura','Mysz','Monitor','Kamera','Drukarka']

ceny = np.array([3499,1899,2499,349,89,249,129,1499,599,899])

ilosci_magazyn = np.array([15,42,78,156,312,89,201,23,45,34])

oceny_klientow = np.array([4.7,4.2,4.5,4.8,3.9,4.1,4.3,4.6,3.8,3.5])

In [23]:
print("Średnia cena:", ceny.mean())

print("Najdroższy:", nazwy[ceny.argmax()], ceny.max())

print("Najtańszy:", nazwy[ceny.argmin()], ceny.min())

Średnia cena: 1171.0
Najdroższy: Laptop 3499
Najtańszy: Ładowarka 89


In [24]:
wartosci = ceny * ilosci_magazyn

print("Wartości produktów:", wartosci)

print("Łączna wartość:", wartosci.sum())

Wartości produktów: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość: 549465


In [25]:
rabat = ceny * 0.85
vat = ceny * 1.23

print("Ceny po rabacie:", rabat)
print("Ceny z VAT:", vat)

print("Produkty powyżej 1000 zł:", (ceny > 1000).sum())

Ceny po rabacie: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny z VAT: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Produkty powyżej 1000 zł: 4


In [26]:
nazwy_np = np.array(nazwy)

maska = oceny_klientow >= 4.5

print("Produkty >=4.5:", nazwy_np[maska])
print("Ceny:", ceny[maska])

Produkty >=4.5: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ceny: [3499 2499  349 1499]


In [27]:
maska = ilosci_magazyn < 30

print("Niski stan:", nazwy_np[maska])

wartosci = ceny * ilosci_magazyn

print("Wartość:", wartosci[maska].sum())

print("Procent magazynu:", wartosci[maska].sum()/wartosci.sum()*100)

Niski stan: ['Laptop' 'Monitor']
Wartość: 86962
Procent magazynu: 15.826667758637946


In [28]:
okazja = (oceny_klientow >= 4.5) & (ceny < 1000)

print("Okazje:", nazwy_np[okazja], ceny[okazja])

print("Średnia cena >=4:", ceny[oceny_klientow >= 4].mean())

print("Średnia cena <4:", ceny[oceny_klientow < 4].mean())

Okazje: ['Słuchawki'] [349]
Średnia cena >=4: 1446.142857142857
Średnia cena <4: 529.0


In [29]:
import time

rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [30]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print("Lista:", czas_lista)
print("NumPy:", czas_numpy)

Lista: 0.04816070800006855
NumPy: 0.006337375001749024


In [31]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print("Lista:", czas_lista)
print("NumPy:", czas_numpy)

Lista: 0.026708874996984378
NumPy: 0.002594541998405475


In [32]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print("Lista:", czas_lista)
print("NumPy:", czas_numpy)

Lista: 0.0577061660005711
NumPy: 0.0030591670001740567


## Wnioski z benchmarku

NumPy jest szybszy od list w operacjach na dużych zbiorach danych.
Operacje wektorowe są dużo wydajniejsze niż pętle w Pythonie.